services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data2:/home/node/.n8n
    networks:
      - n8n-rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq # Nome do serviço RabbitMQ
      - RABBITMQ_PORT=5672     # Porta padrão do RabbitMQ para AMQP
      - RABBITMQ_USER=guest    # Substituir pelo usuário configurado
      - RABBITMQ_PASSWORD=guest # Substituir pela senha configurada
  
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # Porta para comunicação AMQP
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest # Troque pelo usuário desejado
      RABBITMQ_DEFAULT_PASS: guest # Troque pela senha desejada
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq # Persistencia de dados
    #command: /bin/sh -c "chmod 600 /var/lib/rabbintmq/.erlang.cookie && rabbitmq-server"
    networks:
      - n8n-rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postmenino
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-rabbitmq

  
networks:
  n8n-rabbitmq:
    driver: bridge